version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: adopt_dont_shop_test
          POSTGRES_PASSWORD: ""
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
      - ruby/bundle-install
      # Database setup
      - run: bundle exec rake db:create db:schema:load
      # Run the tests
      - run: bundle exec rspec

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy on heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master